<script>
    $( document ).ready(function() {
        $('form[name=type-form]').submit(function(event) {
            var valid = true;
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }

            if ($('select[name=slcArrival]').val() == 0) {
                $('.msg-arrival').text('Country field is required.');
                $('#slcArrival').addClass("border-red");
                valid = false;
            } else {
                $('.msg-arrival').text('');
                $('#slcArrival').removeClass("border-red");
            }
            if ($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            }  else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }

            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });

    });

</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Group Extra Service</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title"><?php if(isset($title)){ echo($title) ; } ?></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="type-form" id="device-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Group extra service name <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["group_name"]) ? $formData["group_name"] : "" ?>"
                                   type="text" id="txtName" name="txtName"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["group_name"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["group_name"]) ? $messages["group_name"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="slcArrival">Arrival <span
                                    class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcArrival" name="slcArrival" class="form-control">
                                <option value="0">Select Arrival...</option>
                                <?= isset($select_arrival) ? $select_arrival : "" ?>
                            </select>
                            <span class="text-danger msg-arrival"><?php echo isset($messages["group_arrival_id"]) ? $messages["group_arrival_id"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Description
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea style="height: 225px;" id="txtDescription" name="txtDescription"
                                      class="form-control"><?php echo isset($formData["group_description"]) ? $formData["group_description"] : "" ?></textarea>
                            <span class="text-danger msg-description"><?php echo isset($messages["group_description"]) ? $messages["group_description"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["group_order"]) ? $formData["group_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["group_order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["group_order"]) ? $messages["group_order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["group_active"]) && $formData["group_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["group_active"]) && $formData["group_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                            <span class="text-danger msg-active"><?php echo isset($messages["group_active"]) ? $messages["group_active"] : "";?></span>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="submit" type="submit" class="btn btn-success">Save</button>
                            <a class="btn btn-primary" href="/groupextraservice">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
