<?php

$urlPage = "?";
if (strlen($this->dispatcher->getParam("slcArrival")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcArrival" => $this->dispatcher->getParam("slcArrival")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Visa Service Fee</h3>
    </div>
</div>
<?php if (isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-2">
                            <h2>Arrival country</h2>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" name="slcArrival" id="slcArrival">
                                <?php
                                echo isset($select_arrival_country) ? $select_arrival_country : "";
                                ?>
                            </select>
                        </div>
                    </div>
                </div>
                <ul class="nav nav-pills" role="tablist">
                    <?php
                    foreach ( $list_type_visa as $type_visa ){
                        $active = $type_visa->getTypeId()== $type_id?"active":"";
                        ?>
                        <li role="presentation" class="<?= $active; ?>">
                            <a href="#<?= $type_visa->getTypeId() ?>visatype"
                               aria-controls="<?= $type_visa->getTypeId() ?>visatype"
                               role="tab"
                               data-toggle="tab"><?= $type_visa->getTypeName() ?></a>
                        </li>
                    <?php } ?>
                </ul>
                <div class="tab-content">
                    <?php foreach ( $list_type_visa as $type_visa ){
                        $active = $type_visa->getTypeId()== $type_id?"active":"";
                        ?>
                        <div role="tabpanel" class="tab-pane <?= $active ?>" id="<?= $type_visa->getTypeId() ?>visatype">
                            <form name="type-form<?= $type_visa->getTypeId() ?>" id="type-form<?= $type_visa->getTypeId() ?>" action=""
                                  data-parsley-validate class="form-horizontal form-label-left" method="post">
                                <input type="hidden" name="txtTypeID" id="txtTypeID" value="<?= $type_visa->getTypeId() ?>" />
                                <div class="ln_solid"></div>
                                <div class="row">
                                    <div class="col-sm">
                                        <h2><strong>Group Applicant</strong></h2>
                                        <?php foreach ($list_group_applicant as $group_applicant ) { ?>
                                            <div class="form-group">
                                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name"><?= $group_applicant->getGroupName() ?> </label>
                                                <div class="col-md-3 col-sm-3 col-xs-6" style="display: flex; align-items: center;">
                                                    <input maxlength="10"
                                                           value="<?= \GlobalVisa\Repositories\VisaFee::getTypeGroupFee($type_visa->getTypeId(),$group_applicant->getGroupId())  ?>"
                                                           type="text" id="txtGroup<?= $group_applicant->getGroupId() ?>" name="txtGroup<?= $group_applicant->getGroupId() ?>"
                                                           class="form-control col-md-3 col-xs-6 text-right"  style="width: 80%">
                                                    <span style="padding-left: 10px; font-weight: bold">USD</span>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <button name="sbmFee<?= $type_visa->getTypeId() ?>" type="submit" class="btn btn-success">
                                            <?php echo 'Save (' . $type_visa->getTypeName().')'; ?>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>

    </div>
<script>
    $(document).ready(function () {
        $("[name='slcArrival']").on('change', function() {
                var slcArrival = $("#slcArrival option:selected").val();
                window.location.href = '/visafee?slcArrival='+slcArrival;
        });
        $('#savechange').click(function () {
            $('form[name=form-type]').prop('action', '<?php echo $this->url->get('/arrivalnationality/save'); ?>');
            $('form[name=form-type]').submit();
        });
    });


</script>